puzzle:
  inventory:
    car:
      #Material of the cars
      material: "STAINED_CLAY"
sign:
  #Sign line where you want to specify the level name
  levelLine: 1
  #Sign line where you want to specify the action (i.e. play, stats)
  actionLine: 2
  #Keywords for the action. (e.g. If the action line contains "play"(default), it will run the play command)
  key:
    play: "play"
    stats: "stats"
stats:
  local:
    #If local stats should be enabled (/rushhour stats)
    enabled: true
#Format for date and time (See https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html for more information)
dateFormat: "dd/MM/yyyy HH:mm"
#Interval of solution moves (20 = 1 second)
solutionInterval: 10