name: RushHour
main: org.inventivetalent.rushhour.RushHour
author: inventivetalent
version: ${project.version}

database: true

softdepend: [MenuBuilder, ItemBuilder, MessageBuilder]

commands:
  rushhour:
    aliases: [rh]